%analytic formula for integrated phase distribution for bipolar gradient 
%profile and N=1.
function retval = phd_int_bip_N1(x)
    retval = (1 - phs(abs(x) - sqrt(3) / 2)) .* sign(x) .* sqrt(2/3) / 24 .* ...
        (4*sqrt(3)*x.^2*(sqrt(2)-atanh(1/sqrt(2))) ...
        + (4*sqrt(3)*x.^2+12*abs(x)+3*sqrt(3)).*atanh(sqrt(1/2-abs(x)/sqrt(3))) ...
        - 9*sqrt(6-4*abs(x)*sqrt(3)) + 2 * abs(x) .* (sqrt(2) * (sqrt(9 - 6*sqrt(3)*abs(x)) - 6) ...
        + 6 * atanh(1/sqrt(2))) - sqrt(3) * 3 * (atanh(1/sqrt(2)) - 3*sqrt(2))) + 0.5 * (1 - phs(-sqrt(3)/2 - x)) + 0.5 * phs(x - sqrt(3)/2);
    
end

